export const examplePrompts = [
    { label: "", value: "" },
    { label: "Chocolate Chip Cookies", value: "Freshly baked cookies with chocolate chips on top. Top down view. Shot using a Hasselblad camera, ISO 100. Professional color grading. Soft shadows. Clean sharp focus. High - end retouching. Food magazine photography"},
    { label: "Cappuccino Cup", value: "steaming cup of cappuccino standing on a table, close-up shot, Coffee beans. The logo made from the coffee on the cup is visible from a slightly angled top-down view. The photo was taken with a professional camera using soft warm lighting, without a flash"},
    { label: "Chicken Burger", value: "a chicken burger, Editorial Photography, Photography, Shot on 70mm lens, Depth of Field, Bokeh, DOF, Tilt Blur, Shutter Speed 1/1000, F/22, White Balance, 32k, Super-Resolution, white background" },
    { label: "Burger", value: "a burger, Cinematic, Editorial Photography, Photography, Shot on 70mm lens, Depth of Field, Bokeh, DOF, Tilt Blur, Shutter Speed 1/1000, F/22, White Balance, 32k, Super-Resolution" },
    { label: "FLying Salad", value: "salad flying through the air with cheese and lettuce, Editorial Photography, Photography, Shot on 70mm lens, Depth of Field, Bokeh, DOF, Tilt Blur, Shutter Speed 1/1000, F/22, White Balance, 32k, Super-Resolution, white background"},
    { label: "Filet Mignon", value: "food photography, filet mignon medium rare with melting butter on top, editorial photography, photography"},
    { label: "Smoked Salmon", value: "A professional food photography of a beautifully plated smoked salmon starter served with horseradish cream and rye bread crisps"},
    { label: "Betroot Carpaccio", value: "A professional food photography of Beetroot carpaccio with a cashew cream dressing served on a slate plate in a vegan Michelin-starred restaurant"},
    { label: "La Vie en Rose", value: "An editorial food photography of the 'La Vie en Rose' dessert with its delicate rose petal meringues and layers of raspberry sorbet and lychee cream, served on a glass platter with a mirrored bottom, in the futuristic and neon-lit dining room of his Shanghai restaurant"},
    { label: "Onion Focaccia", value: "A professional food Photo of Delectable caramelised onion focaccia served with whipped feta cheese and cherry tomatoes, at a table in a Michelin-starred French restaurant with a fusion menu"},
    { label: "Dill Sorbet", value: "Food Photography of Cucumber and Dill Sorbet starter served with a crisp cucumber salad and a drizzle of olive oil, at a table in a Michelin-starred Danish Restaurant"},
    { label: "Beetroot Carpaccio", value: "A food photograph of a vibrant beetroot carpaccio with a cashew cream dressing served on a slate plate in a vegan Michelin-starred restaurant during a summer afternoon."},
    { label: "Sous Vide", value: "A Food Photograph of a sous-vide lamb chop with edible flowers and molecular foam"},
    { label: "Truffle Mac", value: "Editorial food photography of Indulgent black truffle mac and cheese with smoked bacon, served in a rustic cast iron skillet in a Michelin-starred New York restaurant"},
    { label:"Griled Swordfish", value: "hyper-realistic food photography of a Decadent grilled swordfish with a lemon caper butter sauce, served on a bed of creamy polenta in a Michelin-starred New York fish restaurant"},
    { label: "Apple Pie", value: "Professional Food photography with super resolution of Dream desert, apple pie with caramelised apple cubes and cinnamon ice cream" },
    { label: "Fruit Dessert", value: "food photograph of an innovative fruit dessert that uses molecular gastronomy techniques to create a unique texture, featuring a creamy mango puree topped with frozen spheres of coconut water and dusted with a tangy lime powder"},
    { label: "Carved Watermelon Dessert", value: " An editorial  foodphotograph of a stunning fruit dessert featuring a delicately carved watermelon, filled with a refreshing sorbet made from locally sourced berries and topped with edible flowers in a Michelin-starred Copenhagen restaurant"},
    { label: "Margherita Pizza", value: "photorealistic image of a classic Italian Margherita pizza, with a thin, crispy crust, topped with tomato sauce, fresh mozzarella, basil leaves, and a drizzle of extra virgin olive oil"},
    { label: "Tiramisu", value: "mesmerizing food photograph of a delectable tiramisu dessert, with layers of coffee-soaked ladyfingers and creamy mascarpone" },
    { label: "Italian Antipasto Platter", value: "professional food photo of an Italian antipasto platter, with an assortment of cured meats, olives, marinated vegetables, and artisanal bread"},
    { label: "Fruit Platter", value: "photorealistic image of a colorful and exotic tropical fruit platter, showcasing ripe mango, papaya, dragon fruit, and passion fruit"},
    { label: "Texas Barbecue Platter", value: "ultra-realistic photograph of a smoky and flavorful Texas barbecue platter with brisket and sausage links"},
    { label: "Smoothie Bowl", value: "HD photo, trending on Pinterest, colorful fruit smoothie bowl, decorated with an assortment of fresh berries and granola"},
    { label: "Molten Chocolate Cake", value: "mesmerizing food photograph of a molten chocolate lava cake oozing with warm, gooey chocolate, dusted with powdered sugar" },
    { label: "Cheese Platter", value: "professional food photo of a gourmet cheese platter, with an assortment of artisan cheeses, crackers, and fresh fruits" },
    { label: "Gourmet Burger", value: "ultra-realistic photograph of a gourmet burger masterpiece, featuring a juicy beef patty, foie gras, truffle aioli, and edible gold leaf" },
    { label: "Colorful Fruit Tart", value: "full HD, Pinterest-worthy image of a vibrant and colorful fruit tart, adorned with a rainbow of fresh berries, a shiny glaze, and a buttery pastry crust"},
    { label: "Japanese Ramen", value: "photorealistic image, steaming bowl of Japanese ramen, brimming with tender slices of pork, marinated egg, scallions, and a rich, savory broth"},
    { label: "Miso Soup", value: "professional food photo, steaming bowl of miso soup filled with tofu cubes, seaweed, and scallions"},
    { label: "New York Cheesecake", value: "photorealistic image, trending on Pinterest, New York-style cheesecake adorned with a generous layer of strawberry compote and a dusting of powdered sugar"},
    { label: "Green Salad", value: "professional food photography, Greek salad with ripe tomatoes, cucumbers, kalamata olives, red onions, and crumbled feta cheese, drizzled with olive oil and oregano"},
    { label: "Chicken Burger", value: "Chicken burgers, Editorial Photography, Photography Shot on 70mm lens Depth of Field Bokeh DOF Tilt Blur Shutter Speed 1/1000 F/22 White Balance, 32k Super-Resolution white background."},
    { label: "North Indian Cuisine", value: "knolling of north indian cuisine, professional food photography, realistic, depth of field, 4k, highly detailed, heat of the food in the air, close-up shot"},
    { label: "Teppanyaki", value: "Teppanyaki, japanese cuisine, professional Michelin Star gourmet food photography, depth of field"},
    { label: "Chicken Teppanyaki", value: "Chicken Teppanyaki, thinly sliced chicken mixed with a base of soy sauce, roughly grounded red chili, japanese cuisine, professional Michelin Star gourmet food photography, depth of field" },
    { label: "Avocado Ice Cream", value: "professional food photography of an avocado ice cream, dukkah crust, close-up shot, depth of field, shot on Sony ZV-1, gourmet dessert "},
    { label: "Pistachio Baklava", value: "assorted pistachio baklava, epic food photography, shot on 80mm lens, depth of field, tilt blur, f/5.6, white balance, 4k, super-resolution, vignetting "},
    { label: "Egg Tarts", value: "mouthwatering egg tarts served on a grilled plate, pan asian food, gourmet style presentation, stunning food photography, shot on 90 mm lens, depth of field, tilt shift, f/8, white balance, 4k, super-resolution, vivid"},
    { label: "Milk Mousse", value: "Sheep milk mousse, pandan curd and caramelised puffed rice, gourmet, food photography, extreme close-up shot, f/1.2, depth of field, tilt shift, color grading, 32k, super-resolution, vivid"},
    { label: "Yoghurt Mousse", value: "Sheep yoghurt mousse and pandan sponge with caramelised puffed rice, food photography, extreme close-up shot, f/1.2, depth of field, tilt shift, color grading, 32k, super-resolution, vivid "},
    { label: "Iron Man Chocolate", value: "Iron Man sculptor made up of dark chocolate, dessert, smooth, realistic food photography, depth of field, 32k, super-resolution, vivid" },
    { label: "Bannana Cheesecake", value: "Caramelised banana and puffy/ jingly cheese cake, professional Michelin Star gourmet food photography, contemporary, depth of field, 32k, super-resolution, vivid"},
    { label: "Panna Cotta", value: "Panna cotta, Italian dessert, Contemporary, professional Michelin Star gourmet food photography, depth of field "},
    { label: "Italian Dessert", value: "Ultra-realistic Italian desserts line-up, professional Michelin Star gourmet food photography, intricate textures, realistic, depth of field"},
    { label: "Mango Sorbet", value: "mango sorbet, served in a sniffer glass, professional Michelin Star gourmet food photography, macro shot, realistic, depth of field "},
    { label: "Floating Burger", value: "product shot of a burger, floating ingredients, food photography style, professional photo shooting, shot on Sony A7R IV camera, 4k, dynamic"},
    { label: "Bibimbap", value: "overhead food photography, Bibimbap, Korean restaurant, professional shot on Nikon Z7"},
    { label: "Filed Steak", value: "A fiery grilled steak being flipped mid-air, with flames and sparks erupting around it, High-speed photography, food photography, captivating, exciting, Apple iPhone 14 Pro"},
    { label: "Bruschetta", value: "Bruschetta with chard, spinach, poached egg and dukkah plate, on the table outside, shot on Sony Alpha A7R IV, food photography style, macro lens, close up shot, 50mm lens f/ 1.4"},
    { label: "Spaghetti", value: "intentional camera movements, spaghetti pasta in the air, bolognese, professional food photography, realistic, delicious, pasta, food,"},
    { label: "Sushi", value: "a close-up shot of sushi with wasabi, intricate details, ultra-realistic food photography"},
    { label: "Fish BBQ", value: "fish bbq in banana leaf, stunning food photography, shot on 105mm lens, depth of field, tilt shift, f/2.8, accent lighting, 4k, super-resolution, vivid"},
    { label: "Chicken Briyani", value: "a dutch angle close-up shot of large quantity of chicken briyani on a banana leaf, onion raita, water droplets on the leaf, intentional camera movements, shot on Nikon Z7 II, depth of field, tilt shift, f/8, 4k, super-resolution, vivid"},
    { label: "Indian Fermented Food", value: "a pickle served in a spoon from a luxury glass jar, Indian fermented food, ultra-realistic food photography, shot on Sigma 28-70mm lens, f/2.8, 32k, super-resolution, vivid"},
    { label: "Kobe Beef", value: "kobe beef served in the style of salt bae, olive oil, roasted garlic and rosemary leaves, gourmet style presentation, stunning food photography, shot on Tamron 28-75mm lens, f/2.8, depth of field, tilt shift, color grading, 32k, super-resolution, vivid" },
    { label: "Dianne Beef", value: "dutch angle shot of steak Diane, finely chopped beef pieces, mushrooms, and broccoli, green beans, food photography, f/2.8, depth of field, tilt shift, color grading, 32k, super-resolution, vivid"},
    { label: "Healthy Bowl", value: "healthy bowl recipes, assorted, vegetarian food, UHD, 4k, super-resolution, top angle shot, food photography"},
    { label: "Making Pizza", value: "person making pizza in the kitchen preparing ingredients, timeless artistry, dark teal and dark brown, realistic food photography, depth of field, color grading, 32k, super-resolution, vivid"},
    { label: "Wrapped Enoki", value: "bacon-wrapped enoki mushroom, served on an elegant platter, Korean food, food photography, backlight, depth of field, 32k, super-resolution, vivid"},
    { label: "Assorted Macarons", value: "a dozen of colorful assorted macarons, chocolate cascading from top, dynamic, food photography, dim lighting, depth of field, 32k, super-resolution, vivid" },
    { label: "Sonic Hedgehog Food Art", value: "an edible food art of sonic hedgehog, made up of fruits and vegetables, soft lighting, intricate detailing " },
    { label: "Pork BBQ", value: "Overhead food photography, bbq pork with over easy egg rice, Michelin Star restaurant"},
    { label: "Cooked Beefsteak", value: "finely cooked beefsteak, served with broccoli, ginger sauce, mashed potatoes, chopped leeks toppings, chopstick, Japenese steak house, soft lighting, ultimate food photography, extreme close-up shot, 32k, UHD"},
    { label: "Chinese Fish Broth", value: "chinese style fish broth, swirlings, intricate detailing, spoon, top close-up shot, professional Michelin Star gourmet food photography"},
    { label: "Food Box", value: "food photography of food subscription box, depth of field"},
    { label: "Griled Yakiniku", value: "yakiniku being grilled on bbq, smoke, dutch angle shot, Canon PowerShot G7X III, macro shot, natural day lighting, UHD"},
    { label: "Canape", value: "canape dishes on a canape tray, molecular gastronomy, professional Michelin Star gourmet food photography, extreme close-up shot, Fujifilm X-T30 II, 70 mm lens, color grading, super-resolution, 32k" },
    { label: "Sushi Rolls", value: "a dozen of fusion sushi rolls served on an elegant platter, professional Michelin Star gourmet food photography, extreme close-up shot, Nikon Z7 II, color grading, super-resolution, 32k" },
    { label: "Roasted Stuffed Duck", value: "a tenderly roasted stuffed duck cut into slices, The lemon, broccoli, garlic, and rosemary leaves falling from top, ultra-realistic food photography, slow shutter, super-resolution, UHD"},
    { label: "Salmon Fillets", value: "salmon fillets in delicious creamy spinach, olives, and sun-dried sauce, surreal food photography, top angle shot, Sony A7 IV camera, color grading, super-resolution, 32k" },
    { label: "Fermented Jalapeños", value: "Food photography of fermented Jalapeños, Sony A7R IV camera, depth of field, super resolution, dramatic spotlight, 32k"},
    { label: "Natto", value: "extreme close-up shot of sticky Natto served with chopstick, Japanese traditional food, Sony A7R IV camera, depth of field, super-resolution, dramatic spotlight, 32k"},
    { label: "Shiokara", value: "shiokara, Japanese food, professional Michelin Star gourmet food photography, depth of field, diffused lighting, super-resolution, vivid" },
    { label: "Grilled Turkey with Herbs", value: "Juicy grilled turkey seasoned with herbs and spices, baste it with butter, professional Michelin Star gourmet food photography, depth of field, diffused lighting, super-resolution, vivid, perfect baste"},
    { label: "Pork Pie", value: "edible gold wrapped pork pie stacked on each other, gourmet food photography, depth of field, soft, diffused lighting, super-resolution, vivid"},
    { label: "Gold Sushi", value: "gold sushi, edible food, expensive food, gourmet food photography, depth of field, soft, diffused lighting, super-resolution, vivid"},
    { label: "Oysters Topped With Caviar", value: "Oysters Topped With Passion Fruit Caviar, professional Michelin Star gourmet food photography, editorial style, warm, golden lighting, super-resolution, vivid"}
]

export const aspectRatios = [
    { label: "1:1 (default, square)", value: "aspect-[1/1]" },
    { label: "3:4 (Ads, social media)", value: "aspect-[3/4]" },
    { label: "4:3 (TV, photography)", value: "aspect-[4/3]" },
    { label: "16:9 (landscape)", value: "aspect-[16/9]" },
    { label: "9:16 (portrait)", value: "aspect-[9/16]" }
  ];